      
coverage:
  precision: 2
  round: down
  range: "70..100"
  status:
    project:
      default:
        threshold: 5
  ignore:
    - "vendor/*"
    - "make/*"
    - "build/*"
    - "openshift-ci/*"
