ignored-vulnerabilities:
  # Sensitive headers not cleared on cross-origin redirect in net/http
  # Found in Found in: net/http@go1.22.12
  # Fixed in Fixed in: net/http@go1.23.10
  - id: GO-2025-3751
    info: https://pkg.go.dev/vuln/GO-2025-3751
    silence-until: 2025-09-17