ignored-vulnerabilities:
  # Request smuggling due to acceptance of invalid chunked data in net/http
  # Found in Found in: net/http/internal@go1.22.12
  # Fixed in Fixed in: net/http/internal@go1.23.8
  - id: GO-2025-3563
    info: https://pkg.go.dev/vuln/GO-2025-3563
    silence-until: 2025-09-17

  # Incorrect Neutralization of Input During Web Page Generation in x/net in golang.org/x/net
  # Found in Found in: golang.org/x/net/html@v0.33.0
  # Fixed in Fixed in: golang.org/x/net/html@v0.38.0
  - id: GO-2025-3595
    info: https://pkg.go.dev/vuln/GO-2025-3595
    silence-until: 2025-09-17

  # Inconsistent handling of O_CREATE|O_EXCL on Unix and Windows in os in syscall
  # Found in Found in: os@go1.22.12
  # Fixed in Fixed in: os@go1.23.10
  - id: GO-2025-3750
    info: https://pkg.go.dev/vuln/GO-2025-3750
    silence-until: 2025-09-17

  # Sensitive headers not cleared on cross-origin redirect in net/http
  # Found in Found in: net/http@go1.22.12
  # Fixed in Fixed in: net/http@go1.23.10
  - id: GO-2025-3751
    info: https://pkg.go.dev/vuln/GO-2025-3751
    silence-until: 2025-09-17