apiVersion: apps/v1
kind: Deployment
metadata:
  name: registration-service
spec:
  replicas: 3
  selector:
    matchLabels:
      name: registration-service
  template:
    metadata:
      labels:
        name: registration-service
    spec:
      serviceAccountName: registration-service
      containers:
      - name: registration-service
        # Replace this with the built image name
        image: REPLACE_IMAGE
        command:
        - registration-service
        imagePullPolicy: IfNotPresent
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
